### ISSUE TITLE
fastPOSIXct fails to convert seconds with decimals

### ISSUE THREAD

**Issue by MrDrinkwater** [s-u/fasttime#9]
I have to process a very large (several millions rows) timeseries with a 0.1 sec interval.
After importing a file using fread() timestamps are correctly stored as strings:

> "2018-08-29 12:45:00.6"
> "2018-08-29 12:45:00.7"
> "2018-08-29 12:45:00.8"
> "2018-08-29 12:45:00.9"
> "2018-08-29 12:45:01"
> "2018-08-29 12:45:01.1"
> "2018-08-29 12:45:01.2"

Then I tried to convert them to posixct using:
dati1$TIMESTAMP = fastPOSIXct(dati1$TIMESTAMP, tz = "UTC", required.components = 6L)

But looks like something goes wrong, the function still returns decimals of seconds but they look somehow rounded like this:

> 2018-08-29 12:45:00.5
> 2018-08-29 12:45:00.7
> 2018-08-29 12:45:00.7
> 2018-08-29 12:45:00.9
> 2018-08-29 12:45:01.0
> 2018-08-29 12:45:01.0
> 2018-08-29 12:45:01.2
> 2018-08-29 12:45:01.2

Is that a limit of fasttime or a bug?

Thanks

**Comment by s-u** [comment]
The timestamps are not strings, they are `POSIXct` objects. Strings are extremely inefficient - not something you want to use with timestamps on large data. The issue you're seeing has to do with the fact that some of your timestamps cannot be exactly represented (see R FAQ 7.31). For example:

```
> print(as.numeric(fasttime:::fastPOSIXct("2018-08-29 12:45:00.6")), digits=20)
[1] 1535546700.5999999046
```

As you can see `fasttime` gives you the closest possible representation of the timestamp. Note that there result is identical to `as.POSIXct()` as it should be:

```
> print(as.numeric(as.POSIXct("2018-08-29 12:45:00.6")), digits=20)
[1] 1535561100.5999999046

> identical(as.POSIXct("2018-08-29 12:45:00.6","GMT"),
            fasttime:::fastPOSIXct("2018-08-29 12:45:00.6","GMT"))
[1] TRUE
```

So I suspect your issue has nothing to do with `fasttime` but rather how you convert `POSIXct` timestamps to strings. I cannot comment on what `fread` does - it's quite irrelevant here.
